name: Verification

on:
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Apt Packages
      uses: mstksg/get-package@v1
      with:
        apt-get: libboost-test-dev libmpfr-dev libbenchmark-dev
             
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Run benchmark
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ./benchmark/run_benchmarks --benchmark_format=json | tee ${{runner.workspace}}/benchmark_result.json

    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        tool: 'googlecpp'
        output-file-path: ${{runner.workspace}}/benchmark_result.json
        github-token: ${{secrets.GITHUB_TOKEN}}
        auto-push: true
